libname L0 "&L0_PATH.";
libname Ltest "&Ltest_PATH.";

proc surveyselect data=L0.sino_person_certification out=Ltest.sino_person_certification n=10000 noprint;
run;
%macro sampletest(inds=,outds=,baseds=);
	data &outds.;
		if _n_ eq 1 then do;
			if 0 then set &baseds.(keep=iid rename=(iid=ipersonid));
			declare hash cert(dataset:"&baseds.(keep=iid rename=(iid=ipersonid))");
			cert.definekey('ipersonid');
			cert.definedone();
		end;
		set &inds.;
		if not cert.find(key:ipersonid);
	run;
%mend sampletest;
%sampletest(inds=L0.sino_person,outds=Ltest.sino_person,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_person_address,outds=Ltest.sino_person_address,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_person_employment,outds=Ltest.sino_person_employment,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_loan,outds=Ltest.sino_loan,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_loan_apply,outds=Ltest.sino_loan_apply,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_loan_spec_trade,outds=Ltest.sino_loan_spec_trade,baseds=Ltest.sino_person_certification);
%sampletest(inds=L0.sino_credit_record,outds=Ltest.sino_credit_record,baseds=Ltest.sino_person_certification);
proc surveyselect data=L0.sino_credit_record out=work.sino_credit_record n=10000 noprint;
run;
data Ltest.sino_credit_record;
	set Ltest.sino_credit_record work.sino_credit_record;
run;
data Ltest.sino_org;
	set L0.sino_org;
run;
